server:
  port: 8083

spring:
  application:
    name: api-gateway
  cloud:
    discovery:
      enabled: true
    gateway:
      routes:
        - id: customer
          uri: lb://CUSTOMER-SERVICE
          predicates:
            - Path=/customer/**

management:
  tracing:
    sampling:
      probability: 1.0

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
